### ISSUE TITLE
Series rating is empty

### ISSUE THREAD

**Issue by trolley** [UweTrottmann/thetvdb-java#13]
Similar to issue #12 the series rating for Futurama is coming back empty while The TVDB page shows it's TV-14.

**Comment by UweTrottmann** [comment]
Also working fine on my end:
![image](https://user-images.githubusercontent.com/888674/39619165-0dcbd630-4f87-11e8-842c-ab9ff033c458.png)
![image](https://user-images.githubusercontent.com/888674/39619179-24f42bfa-4f87-11e8-92da-d99aa2b65dbb.png)


As said in #12, likely a brief issue at TheTVDB.
