### ISSUE TITLE
Get particular season

### ISSUE THREAD

**Issue by Kashish-Sharma** [UweTrottmann/thetvdb-java#26]
Is there anyway to get episodes season wise or a list of seasons?

I can't find any such endpoint in the API itself.
Or do we have to fetch all the episodes and then handle accordingly ?

**Comment by UweTrottmann** [comment]
I suppose it's possible to first [get a summary of episodes and seasons](https://api.thetvdb.com/swagger#!/Series/get_series_id_episodes_summary), and then [query episodes by season](https://api.thetvdb.com/swagger#!/Series/get_series_id_episodes_query).

**Comment by Kashish-Sharma** [comment]
Thanks a lot! It works
